### ISSUE TITLE
Will this fork get updates?

### ISSUE THREAD

**Issue by gmvoliveira** [AT-UI/feather-font#1]
I implemented this set in a project because I like to manage my icons through scss so was really happy to find this fork! Last week though I was noticing some icons were missing, and after some comparison its clear that this fork isn't complete anymore.

Is there any chance this fork will be updated to add the icons that were added in the original set from colebemis? If not, I'm thinking on switching back to the original implementation of the icons.

**Comment by koppthe** [comment]
ok, I will synchronize missing ICONS today or tomorrow.

**Comment by papakay** [comment]
Thank you @koppthe. awaiting the awesome update to the icon set. Cheers

**Comment by papakay** [comment]
@koppthe please any update with this? Or could you please share how you generate this.

Thank you.

**Comment by koppthe** [comment]
@papakay I will update with this today.

**Comment by gmvoliveira** [comment]
@koppthe thanks for your effort! Will await the update today :)

**Comment by koppthe** [comment]
Done

**Comment by papakay** [comment]
Awesome! Thank you so much.

**Comment by papakay** [comment]
I have tried to generate font icons with icomoon.io but was not successful. Please how do you generate yours? 

Thank you.

**Comment by voxain** [comment]
Hello together, I'm having the same problem as @gmvoliveira when they started this thread - icons are missing. Since I don't know how the font is generated and I'd love to use it in one of my projects, may I ask somebody who has more knowledge than me for an update?
